name: example
description: A new Flutter project.

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  freezed:
    path: ../
  build_runner:
  flutter_test:
    sdk: flutter
  build_verify:
