name: freezed_lint
version: 0.0.1
publish_to: none
environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  analyzer: ^5.0.0
  analyzer_plugin: ^0.11.2
  custom_lint_builder: ^0.2.0
  freezed_annotation: ^2.2.0

dev_dependencies:
  custom_lint: ^0.2.0
