name: freezed_lint
version: 0.0.12
description: >
  Linter rules for freezed.
repository: https://github.com/rrousselGit/freezed
issue_tracker: https://github.com/rrousselGit/freezed/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: '>=9.0.0 <11.0.0'
  analyzer_plugin: ^0.13.0
  custom_lint_builder: ^0.8.0
  freezed_annotation: 3.1.0

dev_dependencies:
  custom_lint: ^0.8.0
  build_verify: ^3.1.0
  test: ^1.22.2
