name: freezed_lint
version: 0.0.1-dev
environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  analyzer: ^5.12.0
  analyzer_plugin: ^0.11.2
  custom_lint_builder: ^0.4.0
  freezed_annotation: ^2.3.0

dev_dependencies:
  custom_lint: ^0.4.0
  build_verify: ^3.1.0
  test: ^1.22.2
