language: bash
os:
  - osx
env:
  - FLUTTER_CHANNEL="stable"
before_script:
  - cd ..
  - git clone https://github.com/flutter/flutter.git -b $FLUTTER_CHANNEL
  - export PATH=$PATH:$PWD/flutter/bin:$PWD/flutter/bin/cache/dart-sdk/bin
  - cd -
  - flutter doctor
script:
  - cd example
  - set -e
  - flutter pub get
  - flutter pub pub run build_runner build --delete-conflicting-outputs
  - flutter test
  - flutter analyze --no-current-package lib test/
  - rm -rf **/*.freezed.dart **/*.g.dart
  - flutter format --set-exit-if-changed --line-length 120 lib test
  - set +e
  - cd -
  - rm -rf example
  - set -e
  - flutter pub get
  - flutter pub pub run build_runner build --delete-conflicting-outputs
  - flutter test
  - flutter analyze --no-current-package lib test/
  - rm -rf **/*.freezed.dart **/*.g.dart
  - flutter format --set-exit-if-changed --line-length 120 lib test

matrix:
  fast_finish: true
cache:
  directories:
    - $HOME/.pub-cache
