name: freezed_annotation
description: >
  Annotations for the freezed code-generator.
  This package does nothing without freezed too.
version: 1.1.0
homepage: https://github.com/rrousselGit/freezed

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  json_annotation: ^4.3.0
  meta: ^1.7.0
