name: freezed_annotation
description: >
  Annotations for the freezed code-generator.
  This package does nothing without freezed too.
version: 0.14.3
homepage: https://github.com/rrousselGit/freezed

environment:
  sdk: ">=2.12.0-0.0.dev <3.0.0"

dependencies:
  collection: ^1.15.0
  json_annotation: ^4.1.0
  meta: ^1.3.0
