name: freezed
description: >
  Code generation for immutable classes that has a simple syntax/API without
  compromising on the features.
version: 0.14.1+2
homepage: https://github.com/rrousselGit/freezed

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.0.0
  build: ^2.0.0
  build_config: ^0.4.2
  meta: ^1.3.0
  source_gen: ^1.0.0
  freezed_annotation: 
    path: ../freezed_annotation/

dev_dependencies:
  json_serializable: ^4.0.0
  json_annotation: ^4.0.0
  build_test: ^2.0.0
  build_runner: ^1.10.3
  test: ^1.16.5
  matcher: ^0.12.10
  source_gen_test: ^1.0.0
