name: freezed
description: >
  Code generation for immutable classes that has a simple syntax/API without
  compromising on the features.
version: 3.2.0
repository: https://github.com/rrousselGit/freezed
issue_tracker: https://github.com/rrousselGit/freezed/issues

environment:
  sdk: ">=3.8.0 <4.0.0"
resolution: workspace

dependencies:
  analyzer: ^8.0.0
  build: ^4.0.0
  build_config: ^1.1.0
  collection: ^1.15.0
  meta: ^1.9.1
  source_gen: ^4.0.0
  freezed_annotation: 3.1.0
  json_annotation: ^4.9.0
  dart_style: ^3.1.0
  pub_semver: ^2.2.0

dev_dependencies:
  json_serializable: ^6.10.0
  build_test: ^3.3.0
  build_runner: ^2.3.3
  test: ^1.21.0
  matcher: ^0.12.14
  source_gen_test: ^1.3.1
  expect_error: ^1.0.10
  flutter:
    sdk: flutter
