name: freezed
description: >
  Code generation for immutable classes that has a simple syntax/API without
  compromising on the features.
version: 0.15.0+1
homepage: https://github.com/rrousselGit/freezed

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  analyzer: ^2.5.0
  build: ^2.0.1
  build_config: ^1.0.0
  collection: ^1.15.0
  meta: ^1.3.0
  source_gen: ^1.0.0
  freezed_annotation: ^0.15.0

dev_dependencies:
  json_serializable: ^5.0.0
  json_annotation: ^4.1.0
  build_test: ^2.1.0
  build_runner: ^2.0.0
  test: ^1.16.8
  matcher: ^0.12.10
  source_gen_test: ^1.0.0
