name: freezed
description: >
  Code generation for immutable classes that has a simple syntax/API without
  compromising on the features.
version: 2.5.7
repository: https://github.com/rrousselGit/freezed
issue_tracker: https://github.com/rrousselGit/freezed/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ">=6.5.0 <7.0.0"
  build: ^2.3.1
  build_config: ^1.1.0
  collection: ^1.15.0
  meta: ^1.9.1
  source_gen: ">=1.4.0 <3.0.0"
  freezed_annotation: ^2.4.4
  json_annotation: ^4.8.0
  # Indirect dependency, but fixes a compiler error when using `pub downgrade`
  dart_style: ^2.3.6

dev_dependencies:
  json_serializable: ^6.3.2
  build_test: ^2.1.5
  build_runner: ^2.3.3
  test: ^1.21.0
  matcher: ^0.12.14
  source_gen_test: ^1.0.6
  expect_error: ^1.0.5
