name: freezed
description: >
  Code generation for immutable classes that has a simple syntax/API without
  compromising on the features.
version: 2.4.8
repository: https://github.com/rrousselGit/freezed
issue_tracker: https://github.com/rrousselGit/freezed/issues

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ">=5.13.0 <7.0.0"
  build: ^2.3.1
  build_config: ^1.1.0
  collection: ^1.15.0
  meta: ^1.9.1
  source_gen: ^1.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.6.0

dev_dependencies:
  json_serializable: ^6.3.2
  build_test: ^2.1.5
  build_runner: ^2.3.3
  test: ^1.21.0
  matcher: ^0.12.14
  source_gen_test: ^1.0.6
  expect_error: ^1.0.5
