name: freezed
description: >
  Code generation for immutable classes that has a simple syntax/API without
  compromising on the features.
version: 0.14.0
homepage: https://github.com/rrousselGit/freezed
publish_to: none # Temp hack, just for the analyzer to ignore `path`

environment:
  sdk: ">=2.12.0-0.0.dev <3.0.0"

dependencies:
  analyzer: ">=0.41.0 <2.0.0"
  build: ^1.6.0
  build_config: ^0.4.2
  meta: ^1.3.0
  source_gen: ^0.9.0
  freezed_annotation:
    path: ../freezed_annotation

dev_dependencies:
  json_serializable: ^4.0.0
  json_annotation: ^4.0.0
  build_test: ^1.2.0
  build_runner: ^1.10.3
  test: ^1.16.5
  matcher: ^0.12.10
  source_gen_test: ^0.1.0
