name: freezed
description: >
  Code generation for immutable classes that has a simple syntax/API without
  compromising on the features.
version: 2.1.0+1
homepage: https://github.com/rrousselGit/freezed

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ">=4.6.0 <5.0.0"
  build: ^2.0.0
  build_config: ^1.0.0
  collection: ^1.15.0
  meta: ^1.7.0
  source_gen: ^1.2.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.4.0

dev_dependencies:
  json_serializable: ^6.1.3
  build_test: ^2.1.5
  build_runner: ^2.1.7
  test: ^1.20.1
  matcher: ^0.12.11
  source_gen_test: ^1.0.2
