name: freezed
description: >
  Code generation for immutable classes that has a simple syntax/API without
  compromising on the features.
version: 1.1.0
homepage: https://github.com/rrousselGit/freezed

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  analyzer: ^2.7.0
  build: ^2.1.1
  build_config: ^1.0.0
  collection: ^1.15.0
  meta: ^1.7.0
  source_gen: ^1.2.0
  freezed_annotation: ^1.0.0

dev_dependencies:
  json_serializable: ^6.0.1
  json_annotation: ^4.3.0
  build_test: ^2.1.4
  build_runner: ^2.1.4
  test: ^1.19.3
  matcher: ^0.12.11
  source_gen_test: ^1.0.1
