name: data_class
description: >
  Code generation for immutable classes that has a simple syntax/API without
  compromising on the features.
version: 3.0.0-0.0.dev
repository: https://github.com/rrousselGit/freezed/tree/data_class
issue_tracker: https://github.com/rrousselGit/freezed/issues

environment: 
  sdk: ">=3.5.0-0.0-dev <4.0.0"

dependencies:
  collection: ^1.18.0
  macros: ^0.1.0-main.5
  meta: ^1.15.0
dev_dependencies:
  analyzer: ^6.5.0
  build_test: ^2.2.2
  test: ^1.25.5
