name: freezed
description: >
  Code generation for immutable classes that has a simple syntax/API without
  compromising on the features.
version: 0.12.1
homepage: https://github.com/rrousselGit/freezed

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: '>=0.39.5 <0.40.0'
  build: ">=0.12.6 <2.0.0"
  build_config: ">=0.4.2 <1.0.0"
  meta: ^1.1.0
  source_gen: ^0.9.0
  freezed_annotation: '>= 0.12.0 <2.0.0'

dev_dependencies:
  json_serializable:
  json_annotation:
  build_test: ^1.2.0
  build_runner: ^1.7.4
  test: ^1.6.0
  matcher: ^0.12.6
  source_gen_test: ^0.1.0
