# The pubspec.yaml of an application using our lints
name: example_app
environment:
  sdk: ">=3.0.0 <4.0.0"
publish_to: none

dependencies:
  freezed_annotation: any

dev_dependencies:
  build_runner: any
  custom_lint: any
  freezed: any
  freezed_lint: any

dependency_overrides:
  freezed_lint:
    path: ../
  freezed_annotation: ^3.0.0
