name: example
description: A new Flutter project.

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation:
    path: ../../freezed_annotation

dev_dependencies:
  freezed:
    path: ../
  json_serializable: ^6.0.1
  build_runner:
  flutter_test:
    sdk: flutter

dependency_overrides:
  freezed:
    path: ../
  freezed_annotation:
    path: ../../freezed_annotation
